version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./data:/data
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     image: wordpress:5.0.2
     volumes:
      - ./wp-content:/var/www/html/wp-content 
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_FS_METHOD: direct
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('FS_METHOD', 'direct);
     depends_on:
       - db
volumes:
    db_data: {}
